FROM ubuntu

RUN apt-get update && apt-get install -y \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY --from=docker:dind /usr/local/bin/docker /usr/local/bin/

WORKDIR /scripts
COPY scripts/netcat_commands.sh /scripts/netcat_commands.sh
EXPOSE 8081
ENTRYPOINT [ "./netcat_commands.sh" ]
CMD [ "/data" ]